# Generated by Django 4.0.4 on 2022-06-18 19:51

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0004_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hospital_conttact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
