# Generated by Django 4.0.4 on 2022-06-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0005_neighbourhood_hospital_conttact_neighbourhood_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='hospital_conttact',
            new_name='hospital_contact',
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.ForeignKey(default='Nairobi', on_delete=django.db.models.deletion.CASCADE, to='NeighbourhoodApp.location'),
        ),
    ]
