# Generated by Django 4.0.4 on 2022-06-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0006_rename_hospital_conttact_neighbourhood_hospital_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='admin',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='area_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeighbourhoodApp.profile'),
        ),
    ]
