# Generated by Django 4.0.4 on 2022-06-19 21:08

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0010_alter_profile_email_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='neighbourhood',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='business',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='NeighbourhoodApp.profile')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
