# Generated by Django 4.0.4 on 2022-06-19 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0011_alter_business_options_alter_neighbourhood_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NeighbourhoodApp.neighbourhood'),
        ),
    ]
