# Generated by Django 4.0.4 on 2022-06-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0012_post_hood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='area_admin',
            new_name='user',
        ),
    ]
