# Generated by Django 4.0.4 on 2022-06-20 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NeighbourhoodApp', '0016_alter_business_hood_alter_post_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NeighbourhoodApp.profile'),
        ),
    ]
